/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as ConnectomeRouteImport } from './routes/connectome'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ExperimentTaskIdRouteImport } from './routes/experiment.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectomeRoute = ConnectomeRouteImport.update({
  id: '/connectome',
  path: '/connectome',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentTaskIdRoute = ExperimentTaskIdRouteImport.update({
  id: '/experiment/$taskId',
  path: '/experiment/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/benchmark': typeof BenchmarkRoute
  '/connectome': typeof ConnectomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/methodology': typeof MethodologyRoute
  '/experiment/$taskId': typeof ExperimentTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/benchmark': typeof BenchmarkRoute
  '/connectome': typeof ConnectomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/methodology': typeof MethodologyRoute
  '/experiment/$taskId': typeof ExperimentTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/benchmark': typeof BenchmarkRoute
  '/connectome': typeof ConnectomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/methodology': typeof MethodologyRoute
  '/experiment/$taskId': typeof ExperimentTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/benchmark'
    | '/connectome'
    | '/how-it-works'
    | '/methodology'
    | '/experiment/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/benchmark'
    | '/connectome'
    | '/how-it-works'
    | '/methodology'
    | '/experiment/$taskId'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/benchmark'
    | '/connectome'
    | '/how-it-works'
    | '/methodology'
    | '/experiment/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  BenchmarkRoute: typeof BenchmarkRoute
  ConnectomeRoute: typeof ConnectomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MethodologyRoute: typeof MethodologyRoute
  ExperimentTaskIdRoute: typeof ExperimentTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectome': {
      id: '/connectome'
      path: '/connectome'
      fullPath: '/connectome'
      preLoaderRoute: typeof ConnectomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment/$taskId': {
      id: '/experiment/$taskId'
      path: '/experiment/$taskId'
      fullPath: '/experiment/$taskId'
      preLoaderRoute: typeof ExperimentTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  BenchmarkRoute: BenchmarkRoute,
  ConnectomeRoute: ConnectomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  MethodologyRoute: MethodologyRoute,
  ExperimentTaskIdRoute: ExperimentTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
